<!DOCTYPE html>
<html lang="en">
<head>
    <?php include('../inc/meta.php'); ?>
    <?php include('../inc/rem.php'); ?>
    <link rel="stylesheet" href="../css/product-240818.css">
    <link rel="stylesheet" href="../css/messageBox-240818.css">
    <title>What is COB Encapsulation Technology | Cinstar LED</title>
    <meta name="description" content="Get an overview of COB technology, its key features, and why it’s vital for LED displays from Cinstar LED. See how it enhances visual performance." />
    <meta name="keywords" content="COB LED, COB technology, LED technology, Cinstar-led, LED display, LED screen, LED video wall, LED screen display, LED display screen, LED screen wall, LED wall display, LED wall video, rental LED display, rental LED screen, commercial LED display, creative LED display manufacturer." />  
</head>
<body class="page-index">
    <?php include('../inc/top.php'); ?>
    <div class="container">
        <div class="content-container blog-content">
            <div class="content">
                <h1 class="title">What is COB Encapsulation Technology?</h1>
                <!-- <div class="date">
                    <span><i class="fa fa-calendar"></i></span>
                    <span>April 18, 2019</span>
                </div> -->
                <div class="img-box">
                    <img src="../images/blog/blog2-1.jpg" alt="COB Encapsulation Technology-1" />
                </div>
                <p>
                COB stands for Chip on Board, is a new encapsulation technology which encapsulates LED chip (rather than LED lamp) directly to PCB board. COB encapsulation technology requires very close cooperations of LED chip industry, LED encapsulation industry and LED display manufacturers. Considering COB encapsulation needs brand new different equipment (encapsulation equipment needs big investment) and the current market for it is not matured yet, it still needs time for its large-scale applications. Here we gonna discuss the advantages of COB technology and the technical problems it facing.
                </p>
                <ul class="list">
                    <li>
                        <div class="sub-title"><i class="fa fa-hand-o-right"></i><h2>Advantages of COB technology</h2></div>
                        <div class="img-box">
                            <img src="../images/blog/blog2-2.jpg" alt="COB Encapsulation Technology-2" />
                        </div>
                        <p class="sub-title"><b>Higher resolution</b></p>
                        <p>
                        Since the LED chips is directly encapsulated to the PCB board, COB LED will be freed from the physical size of SMD and achieve much higher resolution. With COB, the pixel pitch 1mm or lower is possible in the future. 
                        </p>
                        <p class="sub-title"><b>Better anti-collision and durability</b></p>
                        <p>
                        The LED chips is directly encapsulated to the concave surface of PCB and protected by epoxy resin, the whole PCB board is hard and smooth, the incident collision or scratch won’t damage the LEDs. Featuring mask-free design, if gets dirty, it can be cleaned with wet cloth and makes no damage to LEDs.
                        </p>
                        <p class="sub-title"><b>Wider viewing angle</b></p>
                        <p>Adopting COB technology, the viewing angle at any direction is more than 175 degrees, very close to 180 degrees. Besides, it creates better optical light diffusing and light mixing effect. Ensuring better visual experience.</p>
                        <p class="sub-title"><b>Excellent heat dissipation</b></p>
                        <p>
                        LED chip is directly encapsulated to PCB board without any frame, the heat generated by LED chip will be conducted by copper foils on the PCB board. The excellent heat dissipation will slow down the brightness decay of LED chip and prolong the working hours of LED display.
                        </p>
                        <p class="sub-title"><b>Higher stability and usability</b></p>
                        <p>COB adopts high standard coating technology, which protect <a href="../">LED display</a> from any damage caused by water, moisture, dust, oxidation and UV rays etc. It supports all-weather operation and can still be running at extreme temperature condition (-30 to 80 degrees).</p>
                    </li>
                    <li>
                        <div class="sub-title"><i class="fa fa-hand-o-right"></i><h2>Technical problems of COB encapsulation technology</h2></div>
                        <div class="img-box">
                            <img src="../images/blog/blog2-3.jpg" alt="COB Encapsulation Technology-3" />
                        </div>
                        <p class="sub-title"><b>High maintenance cost</b></p>
                        <p>Due to the way of encapsulation, when broken LED happens, it is almost impossible to maintain the single LED. Then you need to get much more spare modules, which increases the purchase cost a lot.</p>
                        <p class="sub-title"><b>Lower color uniformity</b></p>
                        <p>
                        SMD is with better color uniformity. Before soldering, all the SMD will go through sorting machine to be divided into different batches by their brightness and color gamut etc. Only the LEDs from same batch will be used for the screen, which <a href="../products/fine-pitch-led-display.php">ensuring great color and brightness uniformity</a>. Unfortunately, such method can’t be applied to COB.
                        </p>
                        <p class="sub-title"><b>Higher production cost</b></p>
                        <p>Due to the technology limits, it is hard to maintain a high qualification rate. Which in return increases the production cost of COB LED and makes it less competitive than SMD LED.</p>
                        <p>
                        At present, SMD is still the leading role in the display market (pixel pitch >1mm) for its matured and stable product performance, widely recognized application and a complete maintenance system. But with the improvement of COB encapsulation technology, when the market demand goes to 0.5-1mm, the wide application of COB will <a href="../products/fine-pitch-led-display.php">show its great advantages and values</a>.
                        </p>
                    </li>
                </ul>
            </div>
            <?php include('../inc/messageBox.php'); ?>
        </div>
        <?php include('../inc/foot.php'); ?>
    </div>
    <?php include('../inc/js.php'); ?>
    <script>GetCurStyle("led-academy");</script>
</body> 
</html>